"""redacao b2c: tema_catalogo, atribuicao por perfil, risco

Revision ID: 326aa898d291
Revises: 86556a5e2ee2
Create Date: 2026-08-25 09:24:15.472396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '326aa898d291'
down_revision: Union[str, Sequence[str], None] = '86556a5e2ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tema_catalogo',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('faixa_etaria', sa.Text(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('apoio', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('genero', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("faixa_etaria IN ('7-8','9-10','11-12')", name=op.f('ck_tema_catalogo_faixa_valida')),
    sa.CheckConstraint("genero IN ('narrativa','descritiva','opinativa','carta')", name=op.f('ck_tema_catalogo_genero_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tema_catalogo'))
    )
    op.add_column('redacao', sa.Column('risco_sinalizado', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('redacao', sa.Column('risco_motivo', sa.Text(), nullable=True))
    op.add_column('redacao_atribuicao', sa.Column('usuario_id', sa.BigInteger(), nullable=True))
    op.add_column('redacao_atribuicao', sa.Column('origem', sa.Text(), nullable=True))
    op.add_column('redacao_atribuicao', sa.Column('tema_catalogo_id', sa.BigInteger(), nullable=True))
    op.alter_column('redacao_atribuicao', 'turma_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_foreign_key(op.f('fk_redacao_atribuicao_tema_catalogo_id_tema_catalogo'), 'redacao_atribuicao', 'tema_catalogo', ['tema_catalogo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_redacao_atribuicao_usuario_id_usuario'), 'redacao_atribuicao', 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
    # ### fim dos comandos autogerados — CHECKs abaixo (autogenerate não diffa CHECK) ###
    op.create_check_constraint(
        op.f('ck_redacao_atribuicao_turma_xor_usuario'),
        'redacao_atribuicao',
        '(turma_id IS NOT NULL) <> (usuario_id IS NOT NULL)',
    )
    op.create_check_constraint(
        op.f('ck_redacao_atribuicao_origem_valida'),
        'redacao_atribuicao',
        "origem IS NULL OR origem IN ('automatica','sob_demanda')",
    )
    op.drop_constraint(op.f('ck_redacao_status_valido'), 'redacao', type_='check')
    op.create_check_constraint(
        op.f('ck_redacao_status_valido'),
        'redacao',
        "status IN ('enviada','processando','analisada','erro_ingestao','erro_analise','revisao_humana')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_redacao_status_valido'), 'redacao', type_='check')
    op.create_check_constraint(
        op.f('ck_redacao_status_valido'),
        'redacao',
        "status IN ('enviada','processando','analisada','erro_ingestao','erro_analise')",
    )
    op.drop_constraint(op.f('ck_redacao_atribuicao_origem_valida'), 'redacao_atribuicao', type_='check')
    op.drop_constraint(op.f('ck_redacao_atribuicao_turma_xor_usuario'), 'redacao_atribuicao', type_='check')
    op.drop_constraint(op.f('fk_redacao_atribuicao_usuario_id_usuario'), 'redacao_atribuicao', type_='foreignkey')
    op.drop_constraint(op.f('fk_redacao_atribuicao_tema_catalogo_id_tema_catalogo'), 'redacao_atribuicao', type_='foreignkey')
    op.alter_column('redacao_atribuicao', 'turma_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('redacao_atribuicao', 'tema_catalogo_id')
    op.drop_column('redacao_atribuicao', 'origem')
    op.drop_column('redacao_atribuicao', 'usuario_id')
    op.drop_column('redacao', 'risco_motivo')
    op.drop_column('redacao', 'risco_sinalizado')
    op.drop_table('tema_catalogo')
    # ### end Alembic commands ###
