"""identidade familiar b2c: conta, perfil_crianca, papel responsavel

Revision ID: 3bf46f03ff00
Revises: bea8daf60f60
Create Date: 2026-08-24 14:07:37.666902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf46f03ff00'
down_revision: Union[str, Sequence[str], None] = 'bea8daf60f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('responsavel_usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('consentimento_lgpd_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consentimento_versao', sa.Text(), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responsavel_usuario_id'], ['usuario.id'], name=op.f('fk_conta_responsavel_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conta')),
    sa.UniqueConstraint('responsavel_usuario_id', name=op.f('uq_conta_responsavel_usuario_id'))
    )
    op.create_table('perfil_crianca',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('conta_id', sa.BigInteger(), nullable=False),
    sa.Column('apelido', sa.Text(), nullable=False),
    sa.Column('ano_nascimento', sa.Integer(), nullable=False),
    sa.Column('faixa_etaria', sa.Text(), nullable=False),
    sa.Column('ano_escolar', sa.Integer(), nullable=True),
    sa.Column('avatar_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("faixa_etaria IN ('7-8','9-10','11-12')", name=op.f('ck_perfil_crianca_faixa_valida')),
    sa.CheckConstraint('ano_escolar IS NULL OR ano_escolar BETWEEN 1 AND 9', name=op.f('ck_perfil_crianca_ano_escolar_range_b2c')),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], name=op.f('fk_perfil_crianca_conta_id_conta'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_perfil_crianca_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', name=op.f('pk_perfil_crianca'))
    )
    op.add_column('usuario', sa.Column('senha_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Alembic não detecta mudança de TEXTO de CheckConstraint — feito à mão.
    # 'responsavel' entra no papel (identidade familiar B2C).
    op.drop_constraint(op.f('ck_associacao_papel_valido'), 'associacao', type_='check')
    op.create_check_constraint(
        op.f('ck_associacao_papel_valido'),
        'associacao',
        "papel IN ('aluno','responsavel','professor','coordenador','admin')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_associacao_papel_valido'), 'associacao', type_='check')
    op.create_check_constraint(
        op.f('ck_associacao_papel_valido'),
        'associacao',
        "papel IN ('aluno','professor','coordenador','admin')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'senha_hash')
    op.drop_table('perfil_crianca')
    op.drop_table('conta')
    # ### end Alembic commands ###
