"""aluno_questao.conta_sinal (sinal limpo da adaptacao)

Revision ID: 6ef923aa6272
Revises: a2e5c4544465
Create Date: 2026-06-04 01:10:05.263563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef923aa6272'
down_revision: Union[str, Sequence[str], None] = 'a2e5c4544465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluno_questao', sa.Column('conta_sinal', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aluno_questao', 'conta_sinal')
    # ### end Alembic commands ###
