"""assinatura b2c: assinatura, evento_loja

Revision ID: 86556a5e2ee2
Revises: 3bf46f03ff00
Create Date: 2026-08-24 19:49:19.140988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86556a5e2ee2'
down_revision: Union[str, Sequence[str], None] = '3bf46f03ff00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_loja',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('loja', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assinatura_dedup', sa.Text(), nullable=False),
    sa.Column('processado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evento_loja')),
    sa.UniqueConstraint('assinatura_dedup', name=op.f('uq_evento_loja_assinatura_dedup'))
    )
    op.create_table('assinatura',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('conta_id', sa.BigInteger(), nullable=False),
    sa.Column('loja', sa.Text(), nullable=False),
    sa.Column('produto_id', sa.Text(), nullable=False),
    sa.Column('transacao_original_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('em_trial', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ambiente', sa.Text(), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ambiente IN ('sandbox','production')", name=op.f('ck_assinatura_ambiente_valido')),
    sa.CheckConstraint("loja IN ('apple','google')", name=op.f('ck_assinatura_loja_valida')),
    sa.CheckConstraint("status IN ('ativa','em_periodo_de_graca','expirada','cancelada','reembolsada')", name=op.f('ck_assinatura_status_valido')),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], name=op.f('fk_assinatura_conta_id_conta'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assinatura')),
    sa.UniqueConstraint('transacao_original_id', name=op.f('uq_assinatura_transacao_original_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assinatura')
    op.drop_table('evento_loja')
    # ### end Alembic commands ###
