"""bloco1 esquema inicial

Revision ID: a2e5c4544465
Revises: 
Create Date: 2026-06-03 16:29:17.661386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2e5c4544465'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colecionavel',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('asset_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('cartao_postal','carimbo','selo')", name=op.f('ck_colecionavel_tipo_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colecionavel'))
    )
    op.create_table('escola',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escola'))
    )
    op.create_table('pais',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pais'))
    )
    op.create_table('palavra',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('lema', sa.Text(), nullable=False),
    sa.Column('definicao', sa.Text(), nullable=False),
    sa.Column('exemplo_uso', sa.Text(), nullable=False),
    sa.Column('nivel_dificuldade', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('origem', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origem IN ('banco_base','redacao')", name=op.f('ck_palavra_origem_valida')),
    sa.CheckConstraint('nivel_dificuldade BETWEEN 1 AND 10', name=op.f('ck_palavra_nivel_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_palavra')),
    sa.UniqueConstraint('lema', name=op.f('uq_palavra_lema'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.Text(), nullable=True),
    sa.Column('auth_subject', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('auth_provider', 'auth_subject', name='auth_identity')
    )
    op.create_index('uq_usuario_email', 'usuario', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('aluno_colecionavel',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('colecionavel_id', sa.BigInteger(), nullable=False),
    sa.Column('ganho_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['colecionavel_id'], ['colecionavel.id'], name=op.f('fk_aluno_colecionavel_colecionavel_id_colecionavel'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_aluno_colecionavel_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aluno_colecionavel')),
    sa.UniqueConstraint('usuario_id', 'colecionavel_id', name='aluno_colecionavel_unico')
    )
    op.create_table('aluno_palavra',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('palavra_id', sa.BigInteger(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('origem', sa.Text(), nullable=False),
    sa.Column('palavra_gatilho', sa.Text(), nullable=True),
    sa.Column('nivel4_agendado_para', sa.Integer(), nullable=True),
    sa.Column('atribuida_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dominada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('descoberta','nivel_1','nivel_2','nivel_3','nivel_4','dominada')", name=op.f('ck_aluno_palavra_estado_valido')),
    sa.CheckConstraint("origem IN ('pessoal_redacao','sinal_turma','banco_base')", name=op.f('ck_aluno_palavra_origem_valida')),
    sa.ForeignKeyConstraint(['palavra_id'], ['palavra.id'], name=op.f('fk_aluno_palavra_palavra_id_palavra'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_aluno_palavra_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aluno_palavra')),
    sa.UniqueConstraint('usuario_id', 'palavra_id', name='aluno_palavra_unica')
    )
    op.create_table('associacao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('escola_id', sa.BigInteger(), nullable=True),
    sa.Column('papel', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("papel IN ('aluno','professor','coordenador','admin')", name=op.f('ck_associacao_papel_valido')),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], name=op.f('fk_associacao_escola_id_escola'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_associacao_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_associacao'))
    )
    op.create_table('destino',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('pais_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], name=op.f('fk_destino_pais_id_pais'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destino'))
    )
    op.create_table('evento',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_evento_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evento'))
    )
    op.create_table('palavra_sinonimo',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('palavra_id', sa.BigInteger(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['palavra_id'], ['palavra.id'], name=op.f('fk_palavra_sinonimo_palavra_id_palavra'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_palavra_sinonimo'))
    )
    op.create_table('questao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('palavra_id', sa.BigInteger(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('variacao', sa.Text(), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('opcoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resposta_correta', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='ativa', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ativa','oculta_report','em_revisao','removida')", name=op.f('ck_questao_status_valido')),
    sa.CheckConstraint('nivel BETWEEN 1 AND 4', name=op.f('ck_questao_nivel_range')),
    sa.ForeignKeyConstraint(['palavra_id'], ['palavra.id'], name=op.f('fk_questao_palavra_id_palavra'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questao')),
    sa.UniqueConstraint('palavra_id', 'nivel', 'variacao', name='variacao_unica')
    )
    op.create_table('sessao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('xp_ganho', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_sessao_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessao'))
    )
    op.create_table('turma',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('escola_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('ano_escolar', sa.Integer(), nullable=False),
    sa.Column('codigo_turma', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ano_escolar BETWEEN 6 AND 9', name=op.f('ck_turma_ano_escolar_range')),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], name=op.f('fk_turma_escola_id_escola'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turma')),
    sa.UniqueConstraint('codigo_turma', name=op.f('uq_turma_codigo_turma'))
    )
    op.create_table('aluno_questao',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('questao_id', sa.BigInteger(), nullable=False),
    sa.Column('tentativas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('acertou', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('acertou_primeira', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('respondida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], name=op.f('fk_aluno_questao_questao_id_questao'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_aluno_questao_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'questao_id', name=op.f('pk_aluno_questao'))
    )
    op.create_table('associacao_turma',
    sa.Column('associacao_id', sa.BigInteger(), nullable=False),
    sa.Column('turma_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['associacao_id'], ['associacao.id'], name=op.f('fk_associacao_turma_associacao_id_associacao'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], name=op.f('fk_associacao_turma_turma_id_turma'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('associacao_id', 'turma_id', name=op.f('pk_associacao_turma'))
    )
    op.create_table('redacao_atribuicao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('turma_id', sa.BigInteger(), nullable=False),
    sa.Column('professor_associacao_id', sa.BigInteger(), nullable=True),
    sa.Column('tema', sa.Text(), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professor_associacao_id'], ['associacao.id'], name=op.f('fk_redacao_atribuicao_professor_associacao_id_associacao'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], name=op.f('fk_redacao_atribuicao_turma_id_turma'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redacao_atribuicao'))
    )
    op.create_table('report_questao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('questao_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('veredito', sa.Text(), server_default='pendente', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("veredito IN ('pendente','valido','invalido')", name=op.f('ck_report_questao_veredito_valido')),
    sa.ForeignKeyConstraint(['questao_id'], ['questao.id'], name=op.f('fk_report_questao_questao_id_questao'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_report_questao_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_questao'))
    )
    op.create_table('sinal_turma',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('turma_id', sa.BigInteger(), nullable=False),
    sa.Column('palavra_id', sa.BigInteger(), nullable=False),
    sa.Column('periodo', sa.Text(), nullable=False),
    sa.Column('pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('computado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['palavra_id'], ['palavra.id'], name=op.f('fk_sinal_turma_palavra_id_palavra'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], name=op.f('fk_sinal_turma_turma_id_turma'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sinal_turma')),
    sa.UniqueConstraint('turma_id', 'palavra_id', 'periodo', name='sinal_turma_unico')
    )
    op.create_table('trilha_no',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('destino_id', sa.BigInteger(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('xp_limiar', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['destino.id'], name=op.f('fk_trilha_no_destino_id_destino'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trilha_no'))
    )
    op.create_table('turma_config',
    sa.Column('turma_id', sa.BigInteger(), nullable=False),
    sa.Column('meta_semanal', sa.Integer(), nullable=True),
    sa.Column('preset_rigor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], name=op.f('fk_turma_config_turma_id_turma'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('turma_id', name=op.f('pk_turma_config'))
    )
    op.create_table('aluno_progresso',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('xp_total', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('no_atual_id', sa.BigInteger(), nullable=True),
    sa.Column('palavras_dominadas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('combo_atual', sa.Integer(), server_default='0', nullable=False),
    sa.Column('combo_data', sa.Date(), nullable=True),
    sa.Column('nivel_dificuldade_atual', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sessoes_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('nivel_mudou_em_sessao', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nivel_dificuldade_atual BETWEEN 1 AND 10', name=op.f('ck_aluno_progresso_nivel_range')),
    sa.ForeignKeyConstraint(['no_atual_id'], ['trilha_no.id'], name=op.f('fk_aluno_progresso_no_atual_id_trilha_no'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_aluno_progresso_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', name=op.f('pk_aluno_progresso'))
    )
    op.create_table('redacao',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('atribuicao_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('formato', sa.Text(), nullable=False),
    sa.Column('arquivo_ref', sa.Text(), nullable=True),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='enviada', nullable=False),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analisada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("formato IN ('manuscrita','digital')", name=op.f('ck_redacao_formato_valido')),
    sa.CheckConstraint("status IN ('enviada','processando','analisada','erro_ingestao','erro_analise')", name=op.f('ck_redacao_status_valido')),
    sa.ForeignKeyConstraint(['atribuicao_id'], ['redacao_atribuicao.id'], name=op.f('fk_redacao_atribuicao_id_redacao_atribuicao'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_redacao_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redacao'))
    )
    op.create_table('redacao_analise',
    sa.Column('redacao_id', sa.BigInteger(), nullable=False),
    sa.Column('anotacoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['redacao_id'], ['redacao.id'], name=op.f('fk_redacao_analise_redacao_id_redacao'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('redacao_id', name=op.f('pk_redacao_analise'))
    )
    op.create_table('redacao_palavra',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('redacao_id', sa.BigInteger(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('lema', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('virou_atribuicao', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('fraca','superutilizada')", name=op.f('ck_redacao_palavra_tipo_valido')),
    sa.ForeignKeyConstraint(['redacao_id'], ['redacao.id'], name=op.f('fk_redacao_palavra_redacao_id_redacao'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redacao_palavra'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redacao_palavra')
    op.drop_table('redacao_analise')
    op.drop_table('redacao')
    op.drop_table('aluno_progresso')
    op.drop_table('turma_config')
    op.drop_table('trilha_no')
    op.drop_table('sinal_turma')
    op.drop_table('report_questao')
    op.drop_table('redacao_atribuicao')
    op.drop_table('associacao_turma')
    op.drop_table('aluno_questao')
    op.drop_table('turma')
    op.drop_table('sessao')
    op.drop_table('questao')
    op.drop_table('palavra_sinonimo')
    op.drop_table('evento')
    op.drop_table('destino')
    op.drop_table('associacao')
    op.drop_table('aluno_palavra')
    op.drop_table('aluno_colecionavel')
    op.drop_index('uq_usuario_email', table_name='usuario', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_table('usuario')
    op.drop_table('palavra')
    op.drop_table('pais')
    op.drop_table('escola')
    op.drop_table('colecionavel')
    # ### end Alembic commands ###
