"""aluno_colecionavel revelado_em (modo conquista persistido)

Revision ID: bea8daf60f60
Revises: e8d2f7a91c44
Create Date: 2026-07-06 02:56:44.887582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bea8daf60f60'
down_revision: Union[str, Sequence[str], None] = 'e8d2f7a91c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aluno_colecionavel', sa.Column('revelado_em', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aluno_colecionavel', 'revelado_em')
    # ### end Alembic commands ###
