"""Seed do catálogo de temas de redação (Fase 4, `docs/plano_b2c.md` §10.4).

**Catálogo completo: 120 temas (40 por faixa etária)**, como o plano pede —
completado em 26/08 (eram 18, 6 por faixa). Título/gênero/enunciado dos 102
novos foram revisados pelo dono antes da geração do `apoio`; ver
`design/notas-implementacao.md` § "Temas de redação — 18 → 120" (26/08).

Idempotente por `titulo` — mesmo padrão de `seed_vocabulario.py`. Uso:

    python -m app.seed_temas
"""
import asyncio

from sqlalchemy import insert, select

from app import schema
from app.db import engine

TEMAS = [
    # ─────────────────────────────── 7-8 ───────────────────────────────
    {
        "faixa_etaria": "7-8",
        "titulo": "Meu animal favorito",
        "enunciado": "Conte para a gente qual é o seu animal favorito e por quê.",
        "genero": "descritiva",
        "apoio": ["Como ele é?", "Onde ele vive?", "O que você mais gosta nele?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Um dia diferente",
        "enunciado": "Imagine que você acordou e podia voar por um dia. O que você faria?",
        "genero": "narrativa",
        "apoio": ["Pra onde você voaria primeiro?", "Quem você mostraria isso?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Minha comida preferida",
        "enunciado": "Qual é a sua comida preferida? Descreva o gosto, o cheiro e quando você come ela.",
        "genero": "descritiva",
        "apoio": ["Quem faz essa comida pra você?", "Em que ocasião você come ela?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Carta para um amigo",
        "enunciado": "Escreva uma carta contando uma novidade para um amigo ou amiga.",
        "genero": "carta",
        "apoio": ["O que aconteceu?", "Por que essa novidade é importante pra você?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Se eu tivesse um superpoder",
        "enunciado": "Se você pudesse ter um superpoder, qual seria? O que você faria com ele?",
        "genero": "opinativa",
        "apoio": ["Por que esse poder e não outro?", "Você usaria pra ajudar alguém?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Minhas férias dos sonhos",
        "enunciado": "Se você pudesse viajar pra qualquer lugar, pra onde iria? Conte como seria essa viagem.",
        "genero": "narrativa",
        "apoio": ["Com quem você iria?", "O que você faria lá?"],
    },
    # ══════════════════ Conteúdo novo (26/08) — 102 temas ══════════════════
    {
        "faixa_etaria": "7-8",
        "titulo": "Meu lugar preferido de casa",
        "enunciado": "Descreva o cantinho da sua casa onde você mais gosta de ficar.",
        "genero": "descritiva",
        "apoio": ["Como é esse lugar?", "O que você faz lá?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "O dia em que eu fiquei com muito medo",
        "enunciado": "Conte sobre uma vez em que você sentiu bastante medo e o que aconteceu depois.",
        "genero": "narrativa",
        "apoio": ["O que causou o medo?", "Como você se sentiu depois que passou?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Se os animais falassem",
        "enunciado": "Imagine que seu bichinho de estimação (ou um animal que você goste) pudesse falar por um dia. O que ele diria?",
        "genero": "narrativa",
        "apoio": ["O que ele diria primeiro?", "Vocês fariam alguma travessura juntos?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Minha família",
        "enunciado": "Fale sobre as pessoas que moram com você e o que você mais gosta em cada uma.",
        "genero": "descritiva",
        "apoio": ["Quem mora com você?", "O que vocês gostam de fazer juntos?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Um brinquedo que ganhou vida",
        "enunciado": "Imagine que um brinquedo seu ganhou vida durante a noite. O que ele fez?",
        "genero": "narrativa",
        "apoio": ["O que ele fez primeiro?", "Ele quis voltar a ser brinquedo depois?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "A coisa mais engraçada que já aconteceu comigo",
        "enunciado": "Conte uma história engraçada que aconteceu com você ou com alguém da sua família.",
        "genero": "narrativa",
        "apoio": ["Quem estava com você?", "Por que foi tão engraçado?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Se eu fosse um super-herói de verdade",
        "enunciado": "Se você pudesse escolher um poder de herói pra usar na vida real, qual seria e por quê?",
        "genero": "opinativa",
        "apoio": ["Por que esse poder e não outro?", "Como você usaria pra ajudar alguém?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Uma amizade especial",
        "enunciado": "Fale sobre um amigo ou amiga importante pra você e o que vocês gostam de fazer juntos.",
        "genero": "descritiva",
        "apoio": ["O que vocês gostam de fazer juntos?", "O que faz essa amizade especial?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Carta para o Papai Noel (ou aniversário)",
        "enunciado": "Escreva uma carta contando o que você mais gostaria de ganhar e por que isso é importante pra você.",
        "genero": "carta",
        "apoio": ["O que você mais gostaria de ganhar?", "Por que esse presente é importante pra você?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "O dia mais chuvoso do ano",
        "enunciado": "Descreva como é um dia de muita chuva na sua cidade.",
        "genero": "descritiva",
        "apoio": ["Como fica a sua rua na chuva?", "O que você gosta (ou não) de fazer em dias assim?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Se eu encontrasse um dragão",
        "enunciado": "Imagine que você encontrou um dragão no quintal de casa. O que vocês fariam juntos?",
        "genero": "narrativa",
        "apoio": ["Como ele seria?", "O que vocês fariam juntos?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Minha escola",
        "enunciado": "Descreva a sua escola: como ela é, o que você mais gosta e o que mudaria nela.",
        "genero": "descritiva",
        "apoio": ["O que você mais gosta na sua escola?", "O que você mudaria nela?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "O brinquedo que eu mais gosto",
        "enunciado": "Fale sobre o seu brinquedo favorito: como ele é e por que você gosta tanto dele.",
        "genero": "descritiva",
        "apoio": ["Como ele é?", "Desde quando você tem esse brinquedo?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Um passeio inesquecível",
        "enunciado": "Conte sobre um passeio que você fez e nunca esqueceu.",
        "genero": "narrativa",
        "apoio": ["Com quem você foi?", "Por que você nunca esqueceu esse passeio?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Se as plantas pudessem andar",
        "enunciado": "Imagine que as árvores do seu bairro pudessem andar por um dia. O que aconteceria?",
        "genero": "narrativa",
        "apoio": ["Pra onde elas iriam?", "O que aconteceria no seu bairro?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Minha estação do ano favorita",
        "enunciado": "Qual estação do ano (verão, inverno, outono ou primavera) você mais gosta? Por quê?",
        "genero": "opinativa",
        "apoio": ["O que você mais gosta de fazer nessa estação?", "O que diferencia essa estação das outras?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Carta para o meu animal de estimação (real ou dos sonhos)",
        "enunciado": "Escreva uma carta para um animal de estimação contando por que você o ama tanto.",
        "genero": "carta",
        "apoio": ["O que você mais ama nele?", "O que vocês fazem juntos?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Um dia sem telas",
        "enunciado": "Conte como seria um dia inteiro sem celular, tablet ou televisão.",
        "genero": "narrativa",
        "apoio": ["O que você faria no lugar das telas?", "Seria fácil ou difícil pra você?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "A pessoa mais engraçada que eu conheço",
        "enunciado": "Descreva alguém que sempre te faz rir e conte um exemplo de algo engraçado que essa pessoa fez.",
        "genero": "descritiva",
        "apoio": ["O que essa pessoa faz que é engraçado?", "Conte um exemplo de algo que ela fez."],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Se eu achasse um mapa do tesouro",
        "enunciado": "Imagine que você encontrou um mapa do tesouro no seu quintal. Conte a aventura.",
        "genero": "narrativa",
        "apoio": ["Onde o mapa levaria você?", "O que tinha no final da aventura?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Minha comida favorita da escola",
        "enunciado": "Qual é a comida que você mais gosta de levar ou comer na escola? Descreva o sabor.",
        "genero": "descritiva",
        "apoio": ["Qual é o sabor dela?", "Com quem você gosta de comer isso?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Um dia na praia (ou no campo)",
        "enunciado": "Conte como foi (ou como seria) um dia inteiro na praia ou no campo.",
        "genero": "narrativa",
        "apoio": ["O que você fez (ou faria) lá?", "Com quem você estava?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Se eu fosse invisível por um dia",
        "enunciado": "Se você pudesse ficar invisível por um dia, o que faria? É certo usar esse poder pra pregar peças?",
        "genero": "opinativa",
        "apoio": ["O que você faria primeiro?", "É certo usar esse poder pra pregar peças?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Minha cor favorita",
        "enunciado": "Qual é a sua cor favorita? Onde você mais vê ou usa essa cor?",
        "genero": "descritiva",
        "apoio": ["Onde você mais vê essa cor?", "Por que ela é sua favorita?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Uma surpresa que eu recebi",
        "enunciado": "Conte sobre uma surpresa boa que você recebeu (ou gostaria de receber).",
        "genero": "narrativa",
        "apoio": ["Quem preparou a surpresa?", "Como você reagiu?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Carta para um professor",
        "enunciado": "Escreva uma carta para um professor ou professora agradecendo por algo que ele ensinou.",
        "genero": "carta",
        "apoio": ["O que esse professor te ensinou?", "Por que isso foi importante pra você?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "O monstro que mora debaixo da cama",
        "enunciado": "Invente uma história sobre um monstro engraçado (não assustador) que mora debaixo da sua cama.",
        "genero": "narrativa",
        "apoio": ["Como ele é?", "Ele é assustador ou engraçado?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Meu esporte ou brincadeira favorita",
        "enunciado": "Descreva o esporte ou a brincadeira que você mais gosta e como se joga.",
        "genero": "descritiva",
        "apoio": ["Como se joga?", "Com quem você gosta de jogar?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Se eu pudesse escolher um animal de estimação novo",
        "enunciado": "Que animal você escolheria ter como bichinho de estimação? Por quê?",
        "genero": "opinativa",
        "apoio": ["Por que esse animal?", "Como seria cuidar dele?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Um dia de aniversário inesquecível",
        "enunciado": "Conte como foi (ou como seria) o aniversário dos seus sonhos.",
        "genero": "narrativa",
        "apoio": ["O que teve nesse aniversário?", "Quem estava lá?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "A roupa que eu mais gosto de usar",
        "enunciado": "Descreva a roupa ou fantasia que você mais gosta de vestir e por quê.",
        "genero": "descritiva",
        "apoio": ["Como ela é?", "Quando você gosta de usá-la?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Se eu morasse num castelo",
        "enunciado": "Imagine que você mora num castelo por um dia. Como seria a sua rotina?",
        "genero": "narrativa",
        "apoio": ["Como seria o seu quarto?", "O que você faria o dia inteiro?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Uma vez em que eu ajudei alguém",
        "enunciado": "Conte sobre uma vez em que você ajudou alguém e como isso te fez sentir.",
        "genero": "narrativa",
        "apoio": ["Quem você ajudou?", "Como isso te fez sentir?"],
    },
    {
        "faixa_etaria": "7-8",
        "titulo": "Carta para o meu eu de daqui a 1 ano",
        "enunciado": "Escreva uma carta para você mesmo, para ler daqui a um ano. O que você quer lembrar de hoje?",
        "genero": "carta",
        "apoio": ["O que você quer lembrar de hoje?", "O que você espera que tenha mudado?"],
    },
    # ─────────────────────────────── 9-10 ───────────────────────────────
    {
        "faixa_etaria": "9-10",
        "titulo": "Um herói brasileiro",
        "enunciado": "Escolha uma pessoa que você considera um herói brasileiro (real ou de história) e explique por quê.",
        "genero": "opinativa",
        "apoio": ["O que essa pessoa fez de importante?", "O que você aprende com ela?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Se eu pudesse mudar o mundo",
        "enunciado": "Se você pudesse mudar uma coisa no mundo, o que seria e como você faria isso?",
        "genero": "opinativa",
        "apoio": ["Por que isso é importante?", "Quem mais seria ajudado com essa mudança?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Um dia na vida de...",
        "enunciado": "Escolha um animal, objeto ou personagem e conte como seria um dia inteiro na vida dele.",
        "genero": "narrativa",
        "apoio": ["O que ele faz de manhã, tarde e noite?", "O que é mais difícil no dia dele?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Uma invenção incrível",
        "enunciado": "Invente um objeto que ainda não existe e explique para que ele serve e como funciona.",
        "genero": "descritiva",
        "apoio": ["Que problema ele resolve?", "Quem usaria essa invenção?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Carta para o meu eu do futuro",
        "enunciado": "Escreva uma carta para você mesmo, para ler daqui a 5 anos.",
        "genero": "carta",
        "apoio": ["O que você quer lembrar de hoje?", "O que você espera ter conquistado?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "A cidade que eu queria visitar",
        "enunciado": "Escolha uma cidade do mundo que você tem curiosidade de conhecer e explique por quê.",
        "genero": "descritiva",
        "apoio": ["O que você já ouviu falar dela?", "O que você faria no primeiro dia lá?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "O animal em extinção que eu quero proteger",
        "enunciado": "Escolha um animal ameaçado de extinção e explique por que ele merece ser protegido.",
        "genero": "opinativa",
        "apoio": ["Por que esse animal está ameaçado?", "O que pode ser feito pra protegê-lo?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Um dia sem regras",
        "enunciado": "Imagine que por um dia não existisse nenhuma regra em lugar nenhum. Conte o que aconteceria.",
        "genero": "narrativa",
        "apoio": ["O que as pessoas fariam de diferente?", "Isso seria bom ou um caos?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "A importância de reciclar",
        "enunciado": "Na sua opinião, por que é importante reciclar o lixo? Dê exemplos do que já vimos acontecer quando não reciclamos.",
        "genero": "opinativa",
        "apoio": ["O que acontece quando não reciclamos?", "O que você já faz (ou poderia fazer) pra ajudar?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Uma amizade que atravessou uma briga",
        "enunciado": "Conte a história de uma amizade (sua ou inventada) que passou por uma briga e se recuperou.",
        "genero": "narrativa",
        "apoio": ["O que causou a briga?", "Como a amizade se recuperou?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Se eu pudesse conversar com um animal selvagem",
        "enunciado": "Imagine que você pode conversar com um animal selvagem por um dia. O que perguntaria a ele?",
        "genero": "narrativa",
        "apoio": ["Qual animal você escolheria?", "O que você perguntaria a ele?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "A cidade dos meus sonhos",
        "enunciado": "Descreva como seria a cidade perfeita pra você viver.",
        "genero": "descritiva",
        "apoio": ["O que não poderia faltar nela?", "Como seriam as pessoas que moram lá?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Uma injustiça que eu vi ou vivi",
        "enunciado": "Conte sobre uma injustiça que você viu acontecer e o que poderia ter sido diferente.",
        "genero": "opinativa",
        "apoio": ["O que aconteceu exatamente?", "O que poderia ter sido diferente?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Carta para um explorador do passado",
        "enunciado": "Escreva uma carta para um explorador famoso contando como é o mundo hoje.",
        "genero": "carta",
        "apoio": ["O que mais mudou desde a época dele?", "O que você acha que ele acharia estranho hoje?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Se eu governasse por um dia",
        "enunciado": "Se você fosse prefeito da sua cidade por um dia, o que faria primeiro?",
        "genero": "opinativa",
        "apoio": ["Qual seria a primeira decisão?", "Quem seria mais beneficiado?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Uma lenda que eu inventei",
        "enunciado": "Invente uma lenda curta que explique algo da natureza (por que o céu é azul, por que a lua muda de forma, etc.).",
        "genero": "narrativa",
        "apoio": ["O que a lenda explica?", "Quem são os personagens dela?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "O esporte que devia ser olímpico",
        "enunciado": "Escolha uma brincadeira ou esporte que você acha que devia virar modalidade olímpica e explique por quê.",
        "genero": "opinativa",
        "apoio": ["Como se joga essa brincadeira/esporte?", "Por que ela merece virar modalidade olímpica?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Uma viagem no tempo",
        "enunciado": "Se você pudesse viajar no tempo pra qualquer época, pra onde iria e o que faria lá?",
        "genero": "narrativa",
        "apoio": ["Pra que época você iria?", "O que você faria lá?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "O valor da amizade",
        "enunciado": "Na sua opinião, o que faz uma amizade ser de verdade?",
        "genero": "opinativa",
        "apoio": ["Dê um exemplo de amizade de verdade.", "O que quebra a confiança numa amizade?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Um mistério para resolver",
        "enunciado": "Invente uma pequena história de mistério que você (ou um personagem) precisa resolver.",
        "genero": "narrativa",
        "apoio": ["Qual é o mistério?", "Quais pistas ajudam a resolvê-lo?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Se os livros pudessem sair das páginas",
        "enunciado": "Imagine que os personagens de um livro que você leu ganharam vida no seu quarto. O que aconteceria?",
        "genero": "narrativa",
        "apoio": ["Qual personagem apareceria?", "O que ele faria no seu quarto?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Carta para alguém que mora longe",
        "enunciado": "Escreva uma carta para um parente ou amigo que mora longe, contando as novidades.",
        "genero": "carta",
        "apoio": ["Quais novidades você quer contar?", "O que você sente falta dessa pessoa?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Uma regra da escola que eu mudaria",
        "enunciado": "Escolha uma regra da sua escola e explique se ela devia mudar e por quê.",
        "genero": "opinativa",
        "apoio": ["Por que essa regra deveria mudar?", "O que aconteceria se ela mudasse?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "O dia em que a internet caiu no mundo inteiro",
        "enunciado": "Imagine um dia em que a internet parou de funcionar em todo o planeta. O que as pessoas fariam?",
        "genero": "narrativa",
        "apoio": ["Como as pessoas se comunicariam?", "O que mudaria no seu dia a dia?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Minha maior conquista até hoje",
        "enunciado": "Conte sobre algo que você conquistou com esforço e do que mais se orgulha.",
        "genero": "descritiva",
        "apoio": ["O que você fez pra conquistar isso?", "Por que você se orgulha tanto?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Se eu criasse um esporte novo",
        "enunciado": "Invente um esporte novo: explique as regras e como se joga.",
        "genero": "descritiva",
        "apoio": ["Quais são as regras principais?", "Quantas pessoas jogam por vez?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Uma tradição da minha família",
        "enunciado": "Descreva uma tradição ou costume especial da sua família.",
        "genero": "descritiva",
        "apoio": ["Quando essa tradição acontece?", "Por que ela é especial pra sua família?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "O animal mais incrível que existe",
        "enunciado": "Escolha o animal que você acha mais incrível da natureza e explique por quê.",
        "genero": "opinativa",
        "apoio": ["O que ele tem de especial?", "O que ele ensina sobre a natureza?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Carta para um cientista",
        "enunciado": "Escreva uma carta para um cientista (real ou inventado) perguntando sobre uma descoberta que te interessa.",
        "genero": "carta",
        "apoio": ["Que descoberta te interessa?", "O que você gostaria de saber sobre ela?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Se eu tivesse uma máquina de fazer chover",
        "enunciado": "Imagine que você inventou uma máquina que controla o tempo. O que faria (e o que poderia dar errado)?",
        "genero": "narrativa",
        "apoio": ["Quando você usaria a máquina?", "O que poderia dar errado?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Uma competição justa (ou injusta)",
        "enunciado": "Conte a história de uma competição, real ou inventada, e se ela foi justa.",
        "genero": "narrativa",
        "apoio": ["O que aconteceu na competição?", "O que fez ela ser justa ou injusta?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "O que eu faria com um milhão de reais",
        "enunciado": "Se você ganhasse um milhão de reais, o que faria com o dinheiro?",
        "genero": "opinativa",
        "apoio": ["Você guardaria ou gastaria?", "Ajudaria alguém com esse dinheiro?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Se as estações do ano pudessem conversar",
        "enunciado": "Imagine uma conversa entre o verão e o inverno discutindo qual é melhor.",
        "genero": "narrativa",
        "apoio": ["O que cada uma diria a favor de si?", "Quem venceria a discussão?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Uma descoberta que mudou o mundo",
        "enunciado": "Escolha uma invenção ou descoberta importante da história e explique como ela mudou a vida das pessoas.",
        "genero": "descritiva",
        "apoio": ["Como era a vida antes dela?", "Como ficou depois?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "O dia em que eu me perdi",
        "enunciado": "Conte sobre uma vez (real ou inventada) em que você se perdeu e como resolveu a situação.",
        "genero": "narrativa",
        "apoio": ["Onde você estava?", "Como resolveu a situação?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Se eu pudesse ler mentes",
        "enunciado": "Se você pudesse ler a mente das pessoas por um dia, você usaria esse poder? Por quê?",
        "genero": "opinativa",
        "apoio": ["Você usaria esse poder?", "Que problema isso poderia causar?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Uma ilha desconhecida",
        "enunciado": "Invente uma história sobre um naufrágio numa ilha desconhecida e o que os sobreviventes encontram lá.",
        "genero": "narrativa",
        "apoio": ["O que os sobreviventes encontram na ilha?", "Como eles decidem o que fazer?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Meu herói do dia a dia",
        "enunciado": "Fale sobre alguém comum (não famoso) que você considera um herói e por quê.",
        "genero": "descritiva",
        "apoio": ["O que essa pessoa faz de especial?", "Por que ela é um herói pra você?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Carta para o time (ou artista) que eu torço",
        "enunciado": "Escreva uma carta para o time ou artista que você mais admira, contando o que ele significa pra você.",
        "genero": "carta",
        "apoio": ["O que essa torcida/admiração significa pra você?", "O que você gostaria de dizer a eles?"],
    },
    {
        "faixa_etaria": "9-10",
        "titulo": "Se os brinquedos ganhassem consciência",
        "enunciado": "Se os brinquedos tivessem sentimentos, seria certo os jogarmos fora quando enjoamos deles?",
        "genero": "opinativa",
        "apoio": ["Seria certo jogá-los fora?", "O que mudaria na forma como cuidamos deles?"],
    },
    # ─────────────────────────────── 11-12 ───────────────────────────────
    {
        "faixa_etaria": "11-12",
        "titulo": "Tecnologia: amiga ou vilã?",
        "enunciado": "Na sua opinião, a tecnologia ajuda ou atrapalha mais a vida das crianças hoje? Justifique.",
        "genero": "opinativa",
        "apoio": ["Dê um exemplo real.", "Existe um jeito de equilibrar isso?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Uma decisão difícil",
        "enunciado": "Conte sobre uma vez em que você (ou um personagem inventado) teve que tomar uma decisão difícil.",
        "genero": "narrativa",
        "apoio": ["O que estava em jogo?", "O que você aprendeu com essa decisão?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "O planeta daqui a 50 anos",
        "enunciado": "Como você imagina que o planeta vai estar daqui a 50 anos? O que precisa mudar desde já?",
        "genero": "opinativa",
        "apoio": ["Cite um problema ambiental específico.", "O que cada pessoa pode fazer?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Carta para quem vai liderar o país",
        "enunciado": "Escreva uma carta para um futuro presidente com 3 pedidos que você considera importantes.",
        "genero": "carta",
        "apoio": ["Por que esses pedidos e não outros?", "Quem seria beneficiado?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Um livro (ou filme) que mudou como eu penso",
        "enunciado": "Fale sobre um livro, filme ou série que te fez pensar diferente sobre algo.",
        "genero": "opinativa",
        "apoio": ["O que exatamente mudou na sua forma de pensar?", "Você recomendaria pra alguém?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Se eu governasse minha escola por um dia",
        "enunciado": "Se você fosse diretor(a) da sua escola por um dia, o que você mudaria e por quê?",
        "genero": "opinativa",
        "apoio": ["Que problema você resolveria primeiro?", "Como os outros alunos reagiriam?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "As redes sociais fazem bem ou mal na minha idade?",
        "enunciado": "Na sua opinião, redes sociais trazem mais benefícios ou mais riscos pra quem tem a sua idade? Justifique.",
        "genero": "opinativa",
        "apoio": ["Dê um exemplo real.", "Existe um jeito de equilibrar isso?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Um dilema sem resposta fácil",
        "enunciado": "Conte a história de um personagem que precisa escolher entre duas opções, e nenhuma delas é totalmente certa.",
        "genero": "narrativa",
        "apoio": ["Quais são as duas opções?", "O que o personagem aprende com a escolha?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "A desigualdade que eu vejo ao meu redor",
        "enunciado": "Descreva uma desigualdade (social, econômica ou de oportunidades) que você observa perto de você e o que poderia amenizá-la.",
        "genero": "opinativa",
        "apoio": ["Onde você observa essa desigualdade?", "O que poderia amenizá-la?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Carta para quem vai decidir sobre o clima",
        "enunciado": "Escreva uma carta para líderes mundiais pedindo ações concretas contra as mudanças climáticas.",
        "genero": "carta",
        "apoio": ["Que ação concreta você pede?", "Por que isso é urgente?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Se eu pudesse apagar um invento da história",
        "enunciado": "Existe alguma invenção que você acha que trouxe mais problemas do que soluções? Explique.",
        "genero": "opinativa",
        "apoio": ["Que problemas esse invento trouxe?", "Ele também trouxe algo bom?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Uma notícia falsa que se espalhou",
        "enunciado": "Invente (ou conte) a história de uma notícia falsa que se espalhou rápido e o que aconteceu quando a verdade veio à tona.",
        "genero": "narrativa",
        "apoio": ["Como a notícia se espalhou tão rápido?", "O que aconteceu quando a verdade veio à tona?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "O que a minha geração vai fazer diferente",
        "enunciado": "Na sua opinião, o que a sua geração deveria fazer diferente das gerações anteriores?",
        "genero": "opinativa",
        "apoio": ["O que você mudaria em relação às gerações anteriores?", "Por que essa mudança importa?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Uma amizade à distância",
        "enunciado": "Conte a história de uma amizade que se manteve mesmo com a distância física.",
        "genero": "narrativa",
        "apoio": ["Como vocês mantiveram contato?", "O que fez a amizade continuar forte?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "O peso das aparências",
        "enunciado": "Você acha que as pessoas são julgadas demais pela aparência hoje em dia? Dê exemplos.",
        "genero": "opinativa",
        "apoio": ["Dê um exemplo do que você já viu acontecer.", "O que poderia mudar isso?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Carta para o eu que vai fazer 18 anos",
        "enunciado": "Escreva uma carta para você mesmo, para ler no dia em que completar 18 anos.",
        "genero": "carta",
        "apoio": ["O que você quer que essa versão sua lembre?", "Que pergunta você faria a ela?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Um mundo sem escolas",
        "enunciado": "Imagine um mundo onde a escola nunca foi inventada. Como as pessoas aprenderiam as coisas?",
        "genero": "narrativa",
        "apoio": ["Como as pessoas aprenderiam as coisas?", "O que se perderia sem a escola?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "A pressão de ser perfeito",
        "enunciado": "Você sente (ou vê os colegas sentindo) pressão para ser perfeito em tudo? Isso é saudável?",
        "genero": "opinativa",
        "apoio": ["De onde vem essa pressão?", "Isso é saudável ou prejudicial?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Uma decisão que mudou tudo",
        "enunciado": "Conte a história de um personagem cuja vida mudou completamente por causa de uma decisão pequena.",
        "genero": "narrativa",
        "apoio": ["Qual foi a decisão?", "O que teria acontecido se ela tivesse sido diferente?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "O valor do silêncio",
        "enunciado": "Descreva um momento de silêncio que foi importante ou significativo pra você.",
        "genero": "descritiva",
        "apoio": ["Onde e quando aconteceu esse silêncio?", "Por que ele foi importante?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Games: vício ou ferramenta de aprendizado?",
        "enunciado": "Na sua opinião, jogos eletrônicos atrapalham ou ajudam no desenvolvimento de quem joga?",
        "genero": "opinativa",
        "apoio": ["Dê um exemplo de cada lado.", "Onde fica o limite?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Carta para quem vive um bullying",
        "enunciado": "Escreva uma carta de apoio para alguém que está sofrendo bullying na escola.",
        "genero": "carta",
        "apoio": ["Que mensagem de apoio você daria?", "O que você gostaria que essa pessoa soubesse?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "O último dia da Terra como a conhecemos",
        "enunciado": "Imagine (de forma não assustadora) como seria o último dia antes de uma grande mudança no planeta, e o que as pessoas fariam.",
        "genero": "narrativa",
        "apoio": ["O que as pessoas fariam nesse dia?", "O que mudaria depois?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Ser diferente é um problema?",
        "enunciado": "Você acha que a sociedade valoriza ou rejeita quem é diferente? Justifique com exemplos.",
        "genero": "opinativa",
        "apoio": ["Dê um exemplo real.", "O que a sociedade ganharia valorizando as diferenças?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Um erro que virou aprendizado",
        "enunciado": "Conte sobre um erro (seu ou de um personagem) que, no fim, ensinou algo importante.",
        "genero": "narrativa",
        "apoio": ["O que deu errado?", "O que isso ensinou?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "A ética nas competições",
        "enunciado": "Você acha que \"vencer de qualquer jeito\" é aceitável em uma competição? Por quê?",
        "genero": "opinativa",
        "apoio": ["Dê um exemplo de algo que não seria aceitável.", "Vencer justifica qualquer meio?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Se eu pudesse mudar uma lei",
        "enunciado": "Escolha uma lei que você mudaria (ou criaria) e explique como isso ajudaria a sociedade.",
        "genero": "opinativa",
        "apoio": ["Qual lei e por quê?", "Quem seria beneficiado com a mudança?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Uma viagem que virou aprendizado",
        "enunciado": "Conte sobre uma viagem (real ou inventada) que ensinou algo que você não esperava aprender.",
        "genero": "narrativa",
        "apoio": ["O que você não esperava aprender?", "Como isso mudou sua forma de pensar?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "O papel da tecnologia em 2076",
        "enunciado": "Imagine e descreva como a tecnologia vai fazer parte do dia a dia daqui a 50 anos.",
        "genero": "narrativa",
        "apoio": ["O que provavelmente vai existir?", "O que pode ser perdido no caminho?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Carta para um autor que eu admiro",
        "enunciado": "Escreva uma carta para um autor de livro, jogo ou filme que você admira, explicando o impacto da obra na sua vida.",
        "genero": "carta",
        "apoio": ["Qual foi o impacto da obra na sua vida?", "O que você gostaria de perguntar a essa pessoa?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "O que é coragem, de verdade",
        "enunciado": "Na sua opinião, o que realmente significa ser corajoso? Dê um exemplo que não envolva luta ou perigo físico.",
        "genero": "opinativa",
        "apoio": ["Dê um exemplo que não envolva luta ou perigo físico.", "Por que isso conta como coragem?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "A primeira vez que discordei de um adulto",
        "enunciado": "Conte sobre uma vez em que você discordou de um adulto e como lidou com isso.",
        "genero": "narrativa",
        "apoio": ["Sobre o que vocês discordaram?", "Como isso terminou?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Vale a pena competir sempre?",
        "enunciado": "Você acha que a competição constante (nos estudos, nos esportes, nas redes) traz mais benefícios ou mais estresse?",
        "genero": "opinativa",
        "apoio": ["Dê um exemplo de competição saudável e um de prejudicial.", "Onde fica o equilíbrio?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Um mundo mais silencioso ou mais conectado?",
        "enunciado": "Se você pudesse escolher, preferiria um mundo com menos tecnologia e mais silêncio, ou o oposto? Por quê?",
        "genero": "opinativa",
        "apoio": ["O que você ganharia e o que perderia em cada opção?", "Qual pesa mais pra você?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "A história que não está nos livros",
        "enunciado": "Invente a história de alguém comum que viveu um momento histórico importante, mas que ninguém registrou.",
        "genero": "narrativa",
        "apoio": ["Quem é essa pessoa comum?", "Que momento histórico ela viveu?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Carta para uma versão mais nova de mim",
        "enunciado": "Escreva uma carta para a criança que você foi aos 7 anos, contando o que mudou.",
        "genero": "carta",
        "apoio": ["O que mudou desde então?", "O que você diria pra tranquilizá-la?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "O que fazer quando todo mundo discorda de você",
        "enunciado": "Como você lida (ou deveria lidar) quando tem uma opinião diferente da maioria do grupo?",
        "genero": "opinativa",
        "apoio": ["Dê um exemplo real ou possível.", "Vale a pena manter a opinião mesmo sozinho?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Um planeta sem fronteiras",
        "enunciado": "Como seria o mundo se não existissem fronteiras entre países? Isso seria melhor ou pior?",
        "genero": "opinativa",
        "apoio": ["O que melhoraria?", "O que poderia complicar?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "A responsabilidade de quem tem mais",
        "enunciado": "Você acha que quem tem mais recursos (dinheiro, fama, poder) tem mais responsabilidade de ajudar os outros?",
        "genero": "opinativa",
        "apoio": ["Dê um exemplo real.", "Até onde vai essa responsabilidade?"],
    },
    {
        "faixa_etaria": "11-12",
        "titulo": "Um futuro que eu quero construir",
        "enunciado": "Descreva o futuro que você espera construir pra você mesmo daqui a 10 anos.",
        "genero": "descritiva",
        "apoio": ["O que você já está fazendo pra chegar lá?", "O que mais te motiva nesse futuro?"],
    },
]


async def seed_temas() -> dict:
    inseridos = 0
    async with engine.begin() as conn:
        for t in TEMAS:
            existe = (
                await conn.execute(
                    select(schema.tema_catalogo.c.id).where(schema.tema_catalogo.c.titulo == t["titulo"])
                )
            ).scalar_one_or_none()
            if existe is not None:
                continue
            await conn.execute(
                insert(schema.tema_catalogo).values(
                    faixa_etaria=t["faixa_etaria"],
                    titulo=t["titulo"],
                    enunciado=t["enunciado"],
                    genero=t["genero"],
                    apoio=t["apoio"],
                )
            )
            inseridos += 1
    return {"temas_inseridos": inseridos}


if __name__ == "__main__":
    print("seed temas de redação:", asyncio.run(seed_temas()))
